### ISSUE TITLE
Merge to Master Checklist

### ISSUE THREAD

**Issue by madisonmay** [IndicoDataSolutions/Foxhound#6]
- [ ] Tests
- [ ] Documentation (readme.io? inline?)
- [x] Cost functions class interface (like updates and regularization) with default
- [x] Auto-intuit best cost function for highest layer of net (cce = softmax, mse = linear, etc...)
- [ ] knn.py
- [ ] inspect internal state (look at activation)
- [x] stopping functions class interface (like updates and regularization) with default
- [ ] CNN
